# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
r:
  - oldrel
  - release
cache: packages
r_build_args: --no-manual
r_check_args: --no-manual
env:
  global:
    - RGL_USE_NULL=TRUE
addons:
  apt:
    packages:
    - libglu1-mesa-dev
    - libharfbuzz-dev
    - libfribidi-dev
before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
after_success:
  - Rscript -e 'covr::codecov()'
